### ISSUE TITLE
dNSTombstoned issue

### ISSUE THREAD

**Issue by dev-2null** [dirkjanm/adidnsdump#4] opened 2019-05-07 03:05 UTC
Hi, I found that host with attribute dNSTombstoned set to TRUE is still requested whether the --include-tombstoned is specified or not. I got the same issue when I develop C# version of adidnsdump. It works fine with DA account, but a lowpriv user cannot read attributes like dNSTombstoned

![tom](https://user-images.githubusercontent.com/29866226/57268882-1596ab80-70b8-11e9-8e3c-f5b4dc856f9a.png)
![records](https://user-images.githubusercontent.com/29866226/57268888-18919c00-70b8-11e9-99f6-5fd9554279b3.png)

**Comment by dirkjanm** [comment] 2019-05-07 21:11
That is correct, the records are always requested, they just aren't printed if the attribute is visible and the record is tombstoned, unless the flag is specified

**Comment by dirkjanm** [comment] 2019-05-14 19:13
Since this is by design, I'm closing this one.

**Closed as completed by dirkjanm** 2019-05-14 19:13 UTC
